---
title: "Powell Center soilcarbon Template Information"
author: "Grey Monroe"
date: "5/4/2017"
output: html_document
---

### Jump to:
1. [metadata tab](#metadata) 
1. [site tab](#site)
1. [profile tab](#profile) 
1. [layer tab](#layer)
1. [fraction tab](#fraction)

```{r, echo=F}

library(openxlsx)
Template_info_file=system.file("extdata", "Template_info.xlsx", package = "soilcarbon")
sheets<-getSheetNames(Template_info_file)

  metadata<-read.xlsx(Template_info_file , sheet="metadata")
    metadata[is.na(metadata)]<-""
  site<-read.xlsx(Template_info_file , sheet="site")
    site[is.na(site)]<-""
  profile<-read.xlsx(Template_info_file , sheet="profile")
    profile[is.na(profile)]<-""
  layer<-read.xlsx(Template_info_file , sheet="layer")
    layer[is.na(layer)]<-""
  fraction<-read.xlsx(Template_info_file , sheet="fraction")
    fraction[is.na(fraction)]<-""
  
```

# metadata
```{r, echo=F}
library(knitr)
kable(metadata)
```

# site
```{r, echo=F}
library(knitr)
kable(site)
```

# profile
```{r, echo=F}
library(knitr)
kable(profile)
```

# layer
```{r, echo=F}
library(knitr)
kable(layer)
```

# fraction
```{r, echo=F}
library(knitr)
kable(fraction)
```



